"""Short tariff messages in the bot's supported interface languages."""

BILLING_COPY = {
    "ru": ("Тарифы", "Бесплатно — 2 разбора каждые 4 недели. Можно попробовать без оплаты.",
           "Подписка — 40 часов записей на 4 недели за 250 ₽.",
           "Без подписки — покупайте часы, когда нужно: 1 час — 50 ₽, 2 часа — 90 ₽, "
           "3 часа — 125 ₽, 4 часа — 155 ₽.",
           "Оплата пока не подключена. До её запуска бот работает как сейчас.",
           "Рассчитать часы", "Подписка", "Сколько часов разбора рассчитать? Напишите число от 1 до 4, например 1.5.",
           "Введите число от 1 до 4 с точностью до минуты, например 1.5.",
           "{hours} ч разбора — {price} ₽. Оплату подключим позже; сейчас оформить покупку нельзя.",
           "40 часов на 4 недели — 250 ₽. Оплату подключим позже; сейчас оформить подписку нельзя.",
           "Осталось бесплатных разборов за последние 4 недели: {count} из 2."),
    "en": ("Plans", "Free — 2 recordings every 4 weeks. Try the bot at no cost.",
           "Subscription — 40 hours of audio for 4 weeks at ₽250.",
           "Without a subscription — buy hours when you need them: 1 hour — ₽50, "
           "2 hours — ₽90, 3 hours — ₽125, 4 hours — ₽155.",
           "Payments are not available yet. The bot works as usual until they launch.",
           "Calculate hours", "Subscription", "How many hours should I price? Enter 1 to 4, for example 1.5.",
           "Enter 1–4 hours to whole-minute precision, for example 1.5.",
           "{hours} h of recordings — ₽{price}. Payments will be available later.",
           "40 hours for 4 weeks — ₽250. Payments will be available later.",
           "Free recordings remaining in the last 4 weeks: {count} of 2."),
    "de": ("Tarife", "Kostenlos — 2 Aufnahmen alle 4 Wochen. Probiere den Bot gratis aus.",
           "Abo — 40 Stunden Audio für 4 Wochen zum Preis von 250 ₽.",
           "Ohne Abo — kaufe Stunden nach Bedarf: 1 Stunde — 50 ₽, "
           "2 Stunden — 90 ₽, 3 Stunden — 125 ₽, 4 Stunden — 155 ₽.",
           "Zahlungen sind noch nicht verfügbar. Bis dahin funktioniert der Bot wie bisher.",
           "Stunden berechnen", "Abo", "Für wie viele Stunden soll ich den Preis berechnen? Gib 1 bis 4 ein, z. B. 1,5.",
           "Gib 1–4 Stunden minutengenau ein, z. B. 1,5.",
           "{hours} Std. — {price} ₽. Die Zahlung wird später freigeschaltet.",
           "40 Stunden für 4 Wochen — 250 ₽. Die Zahlung wird später freigeschaltet.",
           "Kostenlose Aufnahmen in den letzten 4 Wochen: {count} von 2."),
    "es": ("Planes", "Gratis — 2 grabaciones cada 4 semanas. Prueba el bot sin pagar.",
           "Suscripción — 40 horas de audio durante 4 semanas por 250 ₽.",
           "Sin suscripción — compra horas cuando las necesites: 1 hora — 50 ₽, "
           "2 horas — 90 ₽, 3 horas — 125 ₽, 4 horas — 155 ₽.",
           "Los pagos aún no están disponibles. El bot funciona como siempre hasta entonces.",
           "Calcular horas", "Suscripción", "¿Para cuántas horas calculo el precio? Escribe de 1 a 4, por ejemplo 1,5.",
           "Escribe de 1 a 4 horas con precisión de minutos, por ejemplo 1,5.",
           "{hours} h de grabaciones — {price} ₽. Los pagos llegarán más adelante.",
           "40 horas por 4 semanas — 250 ₽. Los pagos llegarán más adelante.",
           "Grabaciones gratis restantes en las últimas 4 semanas: {count} de 2."),
    "fr": ("Tarifs", "Gratuit — 2 enregistrements toutes les 4 semaines pour essayer.",
           "Abonnement — 40 heures d'audio pendant 4 semaines pour 250 ₽.",
           "Sans abonnement — achète des heures selon tes besoins : 1 heure — 50 ₽, "
           "2 heures — 90 ₽, 3 heures — 125 ₽, 4 heures — 155 ₽.",
           "Le paiement n'est pas encore disponible. Le bot fonctionne comme avant.",
           "Calculer les heures", "Abonnement", "Pour combien d'heures calculer le prix ? Saisis 1 à 4, par exemple 1,5.",
           "Saisis 1 à 4 heures à la minute près, par exemple 1,5.",
           "{hours} h d'enregistrement — {price} ₽. Le paiement sera disponible plus tard.",
           "40 heures pour 4 semaines — 250 ₽. Le paiement sera disponible plus tard.",
           "Enregistrements gratuits restants sur 4 semaines : {count} sur 2."),
    "it": ("Tariffe", "Gratis — 2 registrazioni ogni 4 settimane per provare il bot.",
           "Abbonamento — 40 ore di audio per 4 settimane a 250 ₽.",
           "Senza abbonamento — acquista ore quando servono: 1 ora — 50 ₽, "
           "2 ore — 90 ₽, 3 ore — 125 ₽, 4 ore — 155 ₽.",
           "I pagamenti non sono ancora disponibili. Il bot funziona come prima.",
           "Calcola ore", "Abbonamento", "Per quante ore vuoi calcolare il prezzo? Scrivi da 1 a 4, per esempio 1,5.",
           "Scrivi da 1 a 4 ore con precisione al minuto, per esempio 1,5.",
           "{hours} ore di registrazioni — {price} ₽. I pagamenti arriveranno più avanti.",
           "40 ore per 4 settimane — 250 ₽. I pagamenti arriveranno più avanti.",
           "Registrazioni gratis rimanenti nelle ultime 4 settimane: {count} su 2."),
    "pt": ("Planos", "Grátis — 2 gravações a cada 4 semanas para experimentar.",
           "Assinatura — 40 horas de áudio por 4 semanas a 250 ₽.",
           "Sem assinatura — compre horas quando precisar: 1 hora — 50 ₽, "
           "2 horas — 90 ₽, 3 horas — 125 ₽, 4 horas — 155 ₽.",
           "Os pagamentos ainda não estão disponíveis. O bot funciona como antes.",
           "Calcular horas", "Assinatura", "Para quantas horas quer calcular o preço? Digite de 1 a 4, por exemplo 1,5.",
           "Digite de 1 a 4 horas com precisão de minutos, por exemplo 1,5.",
           "{hours} h de gravações — {price} ₽. Os pagamentos estarão disponíveis depois.",
           "40 horas por 4 semanas — 250 ₽. Os pagamentos estarão disponíveis depois.",
           "Gravações grátis restantes nas últimas 4 semanas: {count} de 2."),
    "tr": ("Tarifeler", "Ücretsiz — her 4 haftada 2 kayıt. Botu ücretsiz dene.",
           "Abonelik — 4 haftalık 40 saat ses kaydı, 250 ₽.",
           "Aboneliksiz — gerektiğinde saat satın al: 1 saat — 50 ₽, "
           "2 saat — 90 ₽, 3 saat — 125 ₽, 4 saat — 155 ₽.",
           "Ödeme henüz kullanılamıyor. O zamana kadar bot eskisi gibi çalışıyor.",
           "Saatleri hesapla", "Abonelik", "Kaç saat için fiyat hesaplayayım? 1 ile 4 arasında yaz, örneğin 1,5.",
           "Dakika hassasiyetinde 1–4 saat yaz, örneğin 1,5.",
           "{hours} saat kayıt — {price} ₽. Ödeme daha sonra açılacak.",
           "4 hafta için 40 saat — 250 ₽. Ödeme daha sonra açılacak.",
           "Son 4 haftada kalan ücretsiz kayıt: 2 üzerinden {count}."),
    "ar": ("الباقات", "مجاناً — تسجيلان كل 4 أسابيع لتجربة الخدمة.",
           "اشتراك — 40 ساعة من التسجيلات لمدة 4 أسابيع مقابل 250 ₽.",
           "بلا اشتراك — اشترِ الساعات عند الحاجة: ساعة — 50 ₽، "
           "ساعتان — 90 ₽، 3 ساعات — 125 ₽، 4 ساعات — 155 ₽.",
           "الدفع غير متاح بعد. سيعمل البوت كالمعتاد حتى تفعيله.",
           "احسب الساعات", "الاشتراك", "لكم ساعة أحسب السعر؟ اكتب رقماً من 1 إلى 4، مثل 1.5.",
           "اكتب من 1 إلى 4 ساعات بدقة الدقيقة، مثل 1.5.",
           "{hours} ساعة من التسجيلات — {price} ₽. سيتاح الدفع لاحقاً.",
           "40 ساعة لأربعة أسابيع — 250 ₽. سيتاح الدفع لاحقاً.",
           "التحليلات المجانية المتبقية خلال 4 أسابيع: {count} من 2."),
    "hi": ("प्लान", "मुफ़्त — हर 4 हफ़्ते में 2 रिकॉर्डिंग। बिना भुगतान आज़माएँ।",
           "सदस्यता — 4 हफ़्तों के लिए 40 घंटे की ऑडियो, 250 ₽ में।",
           "बिना सदस्यता — ज़रूरत पर घंटे खरीदें: 1 घंटा — 50 ₽, "
           "2 घंटे — 90 ₽, 3 घंटे — 125 ₽, 4 घंटे — 155 ₽।",
           "भुगतान अभी उपलब्ध नहीं है। तब तक बॉट पहले की तरह काम करेगा।",
           "घंटे गिनें", "सदस्यता", "कितने घंटों की कीमत चाहिए? 1 से 4 लिखें, जैसे 1.5।",
           "मिनट की सटीकता के साथ 1–4 घंटे लिखें, जैसे 1.5।",
           "{hours} घंटे की रिकॉर्डिंग — {price} ₽। भुगतान बाद में उपलब्ध होगा।",
           "4 हफ्तों के लिए 40 घंटे — 250 ₽। भुगतान बाद में उपलब्ध होगा।",
           "पिछले 4 हफ्तों में बचे मुफ़्त विश्लेषण: 2 में से {count}।"),
    "tk": ("Nyrhnamalar", "Mugt — her 4 hepdede 2 ýazgy. Boty tölegsiz synap gör.",
           "Abuna — 4 hepde üçin 40 sagat audio, bahasy 250 ₽.",
           "Abunasyz — gerek wagty sagat satyn al: 1 sagat — 50 ₽, "
           "2 sagat — 90 ₽, 3 sagat — 125 ₽, 4 sagat — 155 ₽.",
           "Töleg entek elýeterli däl. Şoňa çenli bot öňküsi ýaly işleýär.",
           "Sagatlary hasapla", "Abuna", "Näçe sagadyň bahasyny hasaplaly? 1-den 4-e çenli ýazyň, mysal üçin 1.5.",
           "Minut takyklygynda 1–4 sagat ýazyň, mysal üçin 1.5.",
           "{hours} sagat ýazgy — {price} ₽. Töleg soň elýeterli bolar.",
           "4 hepde üçin 40 sagat — 250 ₽. Töleg soň elýeterli bolar.",
           "Soňky 4 hepdede galan mugt ýazgy: 2-den {count}."),
}
