"""Short tariff messages in the bot's supported interface languages."""

BILLING_COPY = {
    "ru": ("Тарифы", "2 бесплатных разбора за 4 недели", "Подписка: 250 ₽ за 4 недели, 40 часов",
           "Часы без подписки: 1 ч — 50 ₽ · 2 ч — 90 ₽ · 3 ч — 125 ₽ · 4 ч — 155 ₽",
           "Оплата пока не подключена. До её запуска текущий доступ сохраняется.",
           "Купить часы", "Подписка", "Сколько часов разбора хотите купить? Напишите число от 1 до 4, например 1.5.",
           "Введите число от 1 до 4 с точностью до минуты, например 1.5.",
           "{hours} ч разбора — {price} ₽. Оплату подключим позже; сейчас оформить покупку нельзя.",
           "40 часов на 4 недели — 250 ₽. Оплату подключим позже; сейчас оформить подписку нельзя.",
           "Осталось бесплатных разборов за последние 4 недели: {count} из 2."),
    "en": ("Plans", "2 free recordings every 4 weeks", "Subscription: ₽250 for 4 weeks, 40 hours",
           "Hours without a subscription: 1 h — ₽50 · 2 h — ₽90 · 3 h — ₽125 · 4 h — ₽155",
           "Payments are not connected yet. Current access stays available until launch.",
           "Choose hours", "Subscription", "How many hours would you like? Enter 1 to 4, for example 1.5.",
           "Enter 1–4 hours to whole-minute precision, for example 1.5.",
           "{hours} h of recordings — ₽{price}. Payments will be available later.",
           "40 hours for 4 weeks — ₽250. Payments will be available later.",
           "Free recordings remaining in the last 4 weeks: {count} of 2."),
    "de": ("Tarife", "2 kostenlose Aufnahmen alle 4 Wochen", "Abo: 250 ₽ für 4 Wochen, 40 Stunden",
           "Stunden ohne Abo: 1 Std. — 50 ₽ · 2 — 90 ₽ · 3 — 125 ₽ · 4 — 155 ₽",
           "Zahlungen sind noch nicht verfügbar. Der bisherige Zugang bleibt bestehen.",
           "Stunden wählen", "Abo", "Wie viele Stunden möchtest du kaufen? Gib 1 bis 4 ein, z. B. 1,5.",
           "Gib 1–4 Stunden minutengenau ein, z. B. 1,5.",
           "{hours} Std. — {price} ₽. Die Zahlung wird später freigeschaltet.",
           "40 Stunden für 4 Wochen — 250 ₽. Die Zahlung wird später freigeschaltet.",
           "Kostenlose Aufnahmen in den letzten 4 Wochen: {count} von 2."),
    "es": ("Planes", "2 grabaciones gratis cada 4 semanas", "Suscripción: 250 ₽ por 4 semanas, 40 horas",
           "Horas sin suscripción: 1 h — 50 ₽ · 2 h — 90 ₽ · 3 h — 125 ₽ · 4 h — 155 ₽",
           "Los pagos aún no están disponibles. El acceso actual continúa.",
           "Elegir horas", "Suscripción", "¿Cuántas horas quieres comprar? Escribe de 1 a 4, por ejemplo 1,5.",
           "Escribe de 1 a 4 horas con precisión de minutos, por ejemplo 1,5.",
           "{hours} h de grabaciones — {price} ₽. Los pagos llegarán más adelante.",
           "40 horas por 4 semanas — 250 ₽. Los pagos llegarán más adelante.",
           "Grabaciones gratis restantes en las últimas 4 semanas: {count} de 2."),
    "fr": ("Tarifs", "2 enregistrements gratuits toutes les 4 semaines", "Abonnement : 250 ₽ pour 4 semaines, 40 heures",
           "Heures sans abonnement : 1 h — 50 ₽ · 2 h — 90 ₽ · 3 h — 125 ₽ · 4 h — 155 ₽",
           "Le paiement n'est pas encore disponible. L'accès actuel reste ouvert.",
           "Choisir des heures", "Abonnement", "Combien d'heures souhaites-tu acheter ? Saisis 1 à 4, par exemple 1,5.",
           "Saisis 1 à 4 heures à la minute près, par exemple 1,5.",
           "{hours} h d'enregistrement — {price} ₽. Le paiement sera disponible plus tard.",
           "40 heures pour 4 semaines — 250 ₽. Le paiement sera disponible plus tard.",
           "Enregistrements gratuits restants sur 4 semaines : {count} sur 2."),
    "it": ("Tariffe", "2 registrazioni gratis ogni 4 settimane", "Abbonamento: 250 ₽ per 4 settimane, 40 ore",
           "Ore senza abbonamento: 1 h — 50 ₽ · 2 h — 90 ₽ · 3 h — 125 ₽ · 4 h — 155 ₽",
           "I pagamenti non sono ancora disponibili. L'accesso attuale continua.",
           "Scegli ore", "Abbonamento", "Quante ore vuoi acquistare? Scrivi da 1 a 4, per esempio 1,5.",
           "Scrivi da 1 a 4 ore con precisione al minuto, per esempio 1,5.",
           "{hours} ore di registrazioni — {price} ₽. I pagamenti arriveranno più avanti.",
           "40 ore per 4 settimane — 250 ₽. I pagamenti arriveranno più avanti.",
           "Registrazioni gratis rimanenti nelle ultime 4 settimane: {count} su 2."),
    "pt": ("Planos", "2 gravações grátis a cada 4 semanas", "Assinatura: 250 ₽ por 4 semanas, 40 horas",
           "Horas sem assinatura: 1 h — 50 ₽ · 2 h — 90 ₽ · 3 h — 125 ₽ · 4 h — 155 ₽",
           "Os pagamentos ainda não estão disponíveis. O acesso atual continua.",
           "Escolher horas", "Assinatura", "Quantas horas quer comprar? Digite de 1 a 4, por exemplo 1,5.",
           "Digite de 1 a 4 horas com precisão de minutos, por exemplo 1,5.",
           "{hours} h de gravações — {price} ₽. Os pagamentos estarão disponíveis depois.",
           "40 horas por 4 semanas — 250 ₽. Os pagamentos estarão disponíveis depois.",
           "Gravações grátis restantes nas últimas 4 semanas: {count} de 2."),
    "tr": ("Tarifeler", "Her 4 haftada 2 ücretsiz kayıt", "Abonelik: 4 hafta ve 40 saat için 250 ₽",
           "Aboneliksiz saatler: 1 sa — 50 ₽ · 2 sa — 90 ₽ · 3 sa — 125 ₽ · 4 sa — 155 ₽",
           "Ödeme henüz bağlı değil. Mevcut erişim devam ediyor.",
           "Saat seç", "Abonelik", "Kaç saat satın almak istersin? 1 ile 4 arasında yaz, örneğin 1,5.",
           "Dakika hassasiyetinde 1–4 saat yaz, örneğin 1,5.",
           "{hours} saat kayıt — {price} ₽. Ödeme daha sonra açılacak.",
           "4 hafta için 40 saat — 250 ₽. Ödeme daha sonra açılacak.",
           "Son 4 haftada kalan ücretsiz kayıt: 2 üzerinden {count}."),
    "ar": ("الأسعار", "تحليلان مجانيان كل 4 أسابيع", "اشتراك: 250 ₽ لمدة 4 أسابيع و40 ساعة",
           "ساعات بلا اشتراك: ساعة — 50 ₽ · ساعتان — 90 ₽ · 3 — 125 ₽ · 4 — 155 ₽",
           "الدفع غير متاح بعد. الوصول الحالي مستمر.",
           "اختر الساعات", "الاشتراك", "كم ساعة تريد شراءها؟ اكتب رقماً من 1 إلى 4، مثل 1.5.",
           "اكتب من 1 إلى 4 ساعات بدقة الدقيقة، مثل 1.5.",
           "{hours} ساعة من التسجيلات — {price} ₽. سيتاح الدفع لاحقاً.",
           "40 ساعة لأربعة أسابيع — 250 ₽. سيتاح الدفع لاحقاً.",
           "التحليلات المجانية المتبقية خلال 4 أسابيع: {count} من 2."),
    "hi": ("प्लान", "हर 4 हफ्ते में 2 मुफ़्त रिकॉर्डिंग", "सदस्यता: 4 हफ्ते और 40 घंटे के लिए 250 ₽",
           "बिना सदस्यता घंटे: 1 घंटा — 50 ₽ · 2 — 90 ₽ · 3 — 125 ₽ · 4 — 155 ₽",
           "भुगतान अभी उपलब्ध नहीं है। मौजूदा पहुँच जारी रहेगी।",
           "घंटे चुनें", "सदस्यता", "कितने घंटे खरीदना चाहेंगे? 1 से 4 लिखें, जैसे 1.5।",
           "मिनट की सटीकता के साथ 1–4 घंटे लिखें, जैसे 1.5।",
           "{hours} घंटे की रिकॉर्डिंग — {price} ₽। भुगतान बाद में उपलब्ध होगा।",
           "4 हफ्तों के लिए 40 घंटे — 250 ₽। भुगतान बाद में उपलब्ध होगा।",
           "पिछले 4 हफ्तों में बचे मुफ़्त विश्लेषण: 2 में से {count}।"),
    "tk": ("Nyrhnamalar", "Her 4 hepdede 2 mugt ýazgy", "Abuna: 4 hepde we 40 sagat üçin 250 ₽",
           "Abunasyz sagatlar: 1 sag — 50 ₽ · 2 — 90 ₽ · 3 — 125 ₽ · 4 — 155 ₽",
           "Töleg entek elýeterli däl. Häzirki giriş dowam edýär.",
           "Sagat saýla", "Abuna", "Näçe sagat satyn almak isleýärsiňiz? 1-den 4-e çenli ýazyň, mysal üçin 1.5.",
           "Minut takyklygynda 1–4 sagat ýazyň, mysal üçin 1.5.",
           "{hours} sagat ýazgy — {price} ₽. Töleg soň elýeterli bolar.",
           "4 hepde üçin 40 sagat — 250 ₽. Töleg soň elýeterli bolar.",
           "Soňky 4 hepdede galan mugt ýazgy: 2-den {count}."),
}
